# Generated by Django 4.1.3 on 2023-01-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characters',
            new_name='Character',
        ),
    ]
