# Generated by Django 4.1.3 on 2023-01-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_characters_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='species',
            new_name='breed',
        ),
    ]
