# Generated by Django 4.1.3 on 2023-01-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hobby',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
